### ISSUE TITLE
'zlib' is not a text encoding

### ISSUE THREAD

**Issue by OriginalFlavor** [Lattyware/unrpa#10]
I receive the following output

`LookupError: 'zlib' is not a text encoding; use codecs.decode() to handle arbitrary codecs`

**Comment by Lattyware** [comment]
Please provide the full stack trace with the error.

I think, however, that you must be using an old version, please check you are using the latest release (1.5.2). I'm relatively sure that error is already fixed there.

**Comment by Lattyware** [comment]
Given no response, I'm assuming this was just a bug from an old version. If you have run into this issue on the current version please reopen this issue or open a new issue.

**Comment by Ria312** [comment]
q  = pickle.loads(objBody.decode("zlib")).toJSON()
LookupError: 'zlib' is not a text encoding; use codecs.decode() to handle arbitrary codecs

Hi
I am getting this same error.

**Comment by Lattyware** [comment]
Please check the version you are running (`unrpa --version`). It should be `unrpa 2.3.0` if you have the latest version.

The line of code in that error doesn't exist in the latest version of the application, so I suspect you are running an old version of the program.

Please let me know what version you are running, and try with 2.3.0 if you are not using it.

**Comment by Ria312** [comment]
It works now. I tried putting the command like this:

q  = pickle.loads(zlib.decompress(objBody)).toJSON()

This worked.
