### ISSUE TITLE
How did I used '-f'?

### ISSUE THREAD

**Issue by Frederisk** [Lattyware/unrpa#13]
when I used it to unrap a file, CMD said "unrpa: error: file doesn't look like an archive, if you are sure it is, use -f.". But I don't know how to use '-f' to solve this problem. What should I do?

**Comment by Lattyware** [comment]
You can do `unrpa -h` to get help. `-f` takes a version number, e.g: `unrpa -f 3` along with other arguments you need - the versions are `1`, `2` &`3`.

That said, it's highly likely this won't work - an archive should be detectable. There is probably another issue (is it definitely a real RPA archive?).

If you think it is definitely valid and it still doesn't work, you can send me the file (privately to avoid copyright issues if necessary) and I can take a look and see if there is a new version or some other problem.

**Comment by Frederisk** [comment]
It should be a RPA file.

![image](https://user-images.githubusercontent.com/29837738/42674705-64cc1a8c-86a3-11e8-82ea-1e1e0210d4b1.png)

Unfortunately, this approach does not seem to work. It will still display a warning:'-f 1' _zlib.error Error -3 while decompressing data: incorrect header check_ '-f 2'  _ValueError: invalid literal for int() with base 16: b'0000000000e3b7cb f15a4700\n'_  & '-f 3' _zlib.error: Error -5 while decompressing data: incomplete or truncated stream_ : . Perhaps I have to send you the file. how should I send it? Can I use email?

**Comment by Lattyware** [comment]
Your screenshot seems a little suspect, as I don't see an RPA file - it would normally be *inside* the `game` directory, as `archive.rpa` (occasionally other names but always `.rpa`). You can send it to me by email (see my profile) if it is definitely an rpa file.

**Comment by Lattyware** [comment]
I have successfully extracted files from this type of archive - the process isn't automated, but is [described in my comment ](https://github.com/Lattyware/unrpa/issues/15#issuecomment-410186542) on the issue I have made for implementing support for this kind of archive properly.
