### ISSUE TITLE
LookupError: unknown encoding: bytes, python 3.3 is not supported?

### ISSUE THREAD

**Issue by Chtobi** [Lattyware/unrpa#16]
It seems, this script is not fully supports "python 3.x" . I've got this error in Python 3.3.7
```
  File "f:\unrpa.py", line 207, in get_index
    index = pickle.loads(zlib.decompress(f.read()), encoding="bytes")
LookupError: unknown encoding: bytes
```
The reason is simple: python 3.3 doesn't support encoding="bytes" , only encoding="ASCII" So this script requires python 3.4 or later.

**Comment by Lattyware** [comment]
Thanks for the heads-up. I'll fix the documentation to note you need >=3.4.
