### ISSUE TITLE
each instance of"\" in duplicated in the output path

### ISSUE THREAD

**Issue by ajddavid452** [Lattyware/unrpa#17]
Traceback (most recent call last):
  File "unrpa", line 158, in extract_files
    with open(os.path.join(self.path, path), "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ajddavid452\\Documents\\unrpa-1.5.3\\output\\'

btw I am running on 1.6, this happened on 1.5.3 and than I updated to 1.6 and it still happened

**Comment by Lattyware** [comment]
Hrm, if you could send me the archive I can take a look (my email address is on [my profile](https://github.com/Lattyware)). By this point the path should exist, and it should create the file. My guess is maybe some character encoding issue with some filename windows won't make a path from.

**Comment by ajddavid452** [comment]
nevermind I fixed it by adding the "--continue-on-error" parameter

**Comment by Lattyware** [comment]
It is worth noting that you will likely be missing the file this was previously failing on - if that isn't a problem for you, that's great.

If someone comes across this with the same issue but needs the file, then feel free to open a new issue and I'll be happy to investigate.
