### ISSUE TITLE
Archive version is not supported

### ISSUE THREAD

**Issue by TopalovOleg** [Lattyware/unrpa#18]
Using unrpa 2.0.1 (latest from pip) receiving the following:

Auto-detection of the version for this archived failed—it is likely this archive is a version not supported. Try updating unrpa, or submitting a bug report. Header: “RPA-3.2 000000000058accd F 42424240”

**Comment by omegalink12** [comment]
Looks like another custom format. It's not in the renpy github. Can you please provide the name of the game?

**Comment by TopalovOleg** [comment]
Zeliria Sanctuary

**Comment by omegalink12** [comment]
PR was reopened as #20 . Only difference is the addition of 2 chars to the header

**Comment by Lattyware** [comment]
I've pushed a new version (2.1.0) to PyPi containing the change from @omegalink12 supporting this format. Thanks for the report and the fix.
