### ISSUE TITLE
unrpa version does not reflect installed version

### ISSUE THREAD

**Issue by OriginalFlavor** [Lattyware/unrpa#21]
In windows 10, Python 3.7

I installed unrpa using PIP. It looks like version 2.1.0 is installed.

```
C:\Users\User1>pip install "unrpa"
Requirement already satisfied: unrpa in c:\users\lorenpearson\appdata\local\programs\python\python37\lib\site-packages (2.1.0)
```

Then I checked version

```
C:\Users\User1>unrpa --version
unrpa 2.0.1
```
Why isn't the version 2.1.0?

**Comment by omegalink12** [comment]
Looks like the pypi version doesn't completely match master. @Lattyware will have to decide what to do about that.

**Comment by Lattyware** [comment]
Yeah, this must be a mistake on my part, I'll take a look.

**Comment by Lattyware** [comment]
OK, I've set up with the new GitHub actions so it deploys automatically from the tagged release here to PyPI, so hopefully that means the version will always be up-to-date and correct in the future.
