### ISSUE TITLE
new-archive-version.mdHeader: “IndexFn 00000000002e6387 deadbeef”

### ISSUE THREAD

**Issue by MikuPy2001** [Lattyware/unrpa#32]
看起来像是自定义的格式
renpy的版本应该是7.0.1.123
---------------------------------------
Looks like a custom format
Renpy's version should be 7.0.1.123

**Comment by Lattyware** [comment]
Where it is legal and possible to do so, please:
  - Provide the smallest possible archive that doesn't work.
  - Provide `renpy/loader.py`.

You can email me privately with a sample at gareth@lattyware.co.uk if it is an issue to share it publicly.

If you are unable to, please give details on where an example archive can be found.

**Comment by MikuPy2001** [comment]
Thanks, your tips are very useful
I observed that the modification time of the loader.py file is newer
So according to __init__.py and vc_version.py get the version number: 7.0.0.196
Then the differences are compared in the files on the official github
This is indeed a custom version, only the file header is modified 
![ed14e9a1544b240c04b6d5a478b9cf8](https://user-images.githubusercontent.com/29778409/110427982-87d8dc80-80e3-11eb-91c2-043f9d0a5a23.png)
-----------------------
感谢，您的提示非常有用
我观察到 loader.py 文件修改时间较新
于是根据__init__.py和vc_version.py得到了版本号：7.0.0.196
然后在官方github上的文件进行了差异对比
这确实是自定义版本，仅仅修改了文件头
