### ISSUE TITLE
Migrate from optparse to argparse

### ISSUE THREAD

**Issue by medicalwei** [Lattyware/unrpa#8]
The optparse is deprecated 8 years ago. Please migrate the use of optparse to argparse.

https://www.python.org/dev/peps/pep-0389/

Actually my reason is that I am packaging unrpa to [Debian package](https://bugs.debian.org/881686), which requires manpage for your script.  I am using sphinx to generate the documents from the binary, with sphinx-argparse, but found out you are using optparse which is not compatible to it.

**Comment by Lattyware** [comment]
I've gone ahead and done that. This script was written a long time ago, but I should have caught the use of optparse when bumping to Python 3.x. Cheers for the heads-up, and thanks for packaging. I'd be happy to add a reference to the fact a package is available in the readme, if you let me know.
