### ISSUE TITLE
Kinda little problem

### ISSUE THREAD

**Issue by NismoW** [Lattyware/unrpa#9]
It keep saying "SyntaxError: unexpected character after line continuation character" for no reason, someone help? (also I am noob)

**Comment by Lattyware** [comment]
I assume this is because you are trying to run with Python 2, not Python 3.

Using the correct launcher for your system should ensure you use Python 3 and fix this problem. You will need to [install Python 3](https://www.python.org/downloads/) if it isn't installed already.

> On most unix systems, open a terminal, then: python3 unrpa -mp "path/to/output/dir" "path/to/archive.rpa"
> On most Windows systems, open a Command Prompt, then: py -3 unrpa -mp "path\to\output\dir" "path\to\archive.rpa"

**Comment by Lattyware** [comment]
I'll close this issue as you haven't replied - if you run into problems still, please open a new issue.
